# Generated by Django 5.0 on 2024-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_emailaddress_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='emailis_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phoneis_verified',
            field=models.BooleanField(default=False),
        ),
    ]
